# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b36b9aab0bfe021d16c1a2431da9e1755721caaf674d84cd84966b2f4d79df200916b8950d7899b4396f3be8b3439f2ba77619ff30f528b6c69d986381acd15

test:
  secret_key_base: 07fae2cae49b91be675c3c05b0fb9205ccd25ed64d2af1fdf5d1e5809df51967eb947f74d1ea745968a8edc35230f50b6ca1227b3e943df4cb0d77f667a608ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
